; "Codewords for Necklace of Skulls"

<OBJECT CODEWORD-ANGEL
    (DESC "Angel")
    (SYNONYM ANGEL)>

<OBJECT CODEWORD-PAKAL
    (DESC "Pakal")
    (SYNONYM PAKAL)>

<OBJECT CODEWORD-SALVATION
    (DESC "Salvation")
    (SYNONYM SALVATION)>

<OBJECT CODEWORD-VENUS
    (DESC "Venus")
    (SYNONYM VENUS)>