"Necklace of Skulls (ZIL)"

<CONSTANT GAME-TITLE "||Necklace of Skulls">
<CONSTANT GAME-DESCRIPTION "|Dave Morris (1993)||Implemented in ZIL by SD Separa (2020)|">
<CONSTANT RELEASEID 6>
<CONSTANT IFID "A1609EC7-2CD6-463F-9C52-D157A9FAC478">
<VERSION XZIP>

<INSERT-FILE "minilib">
<INSERT-FILE "story">

<ROUTINE GO ()
    <V-VERSION>
    <TELL CR "IFID: ">
    <TELL IFID>
    <CRLF>
    <GAME-BOOK>
    <QUIT-MSG>>
